# Generated by Django 5.2 on 2025-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desciption', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
