# Generated by Django 5.2 on 2025-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desciption_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='desciption_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='desciption_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
